name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - pytest=6.2.2
  - scipy=1.6.1
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - jinja2>3.1.0
  - pip:
      - wandb==0.13.9